version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=rahasiaalumnisuperaman123
      - DATABASE_URL="file:./dev.db"
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
